### ISSUE TITLE
traceback when using same name (DNS) -> no info about created machine displayed

### ISSUE THREAD

**Issue by jscotka** [simon3z/virt-deploy#4]
Hi,
I've created machine via:
 # virt-deploy teste fedora-21
Then I've removed machine via virt-manager (delete) that created guest
next command with same name:
 # virt-deploy teste fedora-21
thows traceback althoung machine is probably properly created (this traceback should be suppressed):
 libvirt.libvirtError: Requested operation is not valid: there is already at least one DNS HOST record with a matching field in network default

But it causes that info about machine is not displayed , so that I dont know root password 
name: teste-fedora-21-x86_64
root password: testvm
mac address: 52:54:00:43:98:d6
hostname: localhost
ip address: 1.1.1.1

```
  Regards
  Honza
```

Traceback (most recent call last):
  File "/bin/virt-deploy", line 9, in <module>
    load_entry_point('virtdeploy==0.1.5', 'console_scripts', 'virt-deploy')()
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 135, in main
    return parse_command_line(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 130, in parse_command_line
    return COMMAND_TABLE[args.command](args)
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 37, in instance_create
    instance = driver.instance_create(args.id, args.template)
  File "/usr/lib/python2.7/site-packages/virtdeploy/drivers/libvirt.py", line 190, in instance_create
    _add_network_host(net, hostname, ipaddress)
  File "/usr/lib/python2.7/site-packages/virtdeploy/drivers/libvirt.py", line 300, in _add_network_host
    _NET_UPDATE_FLAGS)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 2867, in update
    if ret == -1: raise libvirtError ('virNetworkUpdate() failed', net=self)
libvirt.libvirtError: Requested operation is not valid: there is already at least one DNS HOST record with a matching field in network default

**Comment by simon3z** [comment]
@jscotka removing the VM from virt-manager is not supported because it is not removing everything (dns, dhcp, etc.). You should remove the instance using

```
$ virt-deploy delete vm-name
```

**Comment by jscotka** [comment]
Hi,
but is seems to be almost working, machine is created, initialized, but at the end there is only problem that I don't know root password for that created host, because of missing summary.

virt-deploy create testcc fedora-21 
Formatting 'testcc-fedora-21-x86_64.qcow2', fmt=qcow2 size=21474836480 backing_file='_fedora-21-x86_64.qcow2' encryption=off cluster_size=65536 lazy_refcounts=off 
[   0.0] Examining the guest ...
[  15.0] Setting a random seed
[  15.0] Setting the hostname: vm-testcc
[  15.0] Setting passwords
[  16.0] Finishing off
Traceback (most recent call last):
  File "/bin/virt-deploy", line 9, in <module>
    load_entry_point('virtdeploy==0.1.5', 'console_scripts', 'virt-deploy')()
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 135, in main
    return parse_command_line(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 130, in parse_command_line
    return COMMAND_TABLE[args.command](args)
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 37, in instance_create
    instance = driver.instance_create(args.id, args.template)
  File "/usr/lib/python2.7/site-packages/virtdeploy/drivers/libvirt.py", line 190, in instance_create
    _add_network_host(net, hostname, ipaddress)
  File "/usr/lib/python2.7/site-packages/virtdeploy/drivers/libvirt.py", line 300, in _add_network_host
    _NET_UPDATE_FLAGS)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 2867, in update
    if ret == -1: raise libvirtError ('virNetworkUpdate() failed', net=self)
libvirt.libvirtError: Requested operation is not valid: there is already at least one DNS HOST record with a matching field in network default

**Comment by simon3z** [comment]
@jscotka because the previous machine was not removed with:

```
$ virt-deploy delete vm-name
```

Now you have to manually edit:

```
$ virsh net-edit default
```

to remove the dns entry

**Comment by jscotka** [comment]
Yes I understand, but my question or requirements is to take care about that traceback. There are two solution:
1. Do not allow to create machine with name what was used -> so that machine will not be created anyway
2. Take care about this traceback and in case it is thrown -> handle it somehow (repair DNS host names, or check it before and in case it exist count with DNS host names like, set MAC IP against it)

Use case is that someone uses virt-deploy for single instance creation in some script -> play with machine in virt-manager -> machine is damaged -> delete it (forgotten that virt-deploy exist, because user is playing with virt-manager on first place) 
===>     It leads to, machine with same name is created, but user don't know how to log in there, because he does not  have root PASSWORD, (evething other is same)

Using virt-deploy should be as easy as possibe in that case.
