### ISSUE TITLE
RFE: add new option to wait for guest is ready to communicate (ping, ssh, ...)

### ISSUE THREAD

**Issue by jscotka** [simon3z/virt-deploy#5]
Hi,
I had to done my own workaround around function, what wait until machine is started (ssh is ready to communicate) https://github.com/jscotka/cockpit/blob/new_test_structure/test/tests/lib/create_test_machine.sh#L93
It would be nice to add param to virt-deploy start command (what will wait until for example ping, or ssh is working) or second solution is to write dedicated function for that like my vm_wait_online

see actual results (first 11 pings are lost because machine is not booted well):

[root@unused-4-228 tests]# virt-deploy stop $NAME
[root@unused-4-228 tests]# virt-deploy start $NAME; ping -c 15 $IP
PING 192.168.122.35 (192.168.122.35) 56(84) bytes of data.
64 bytes from 192.168.122.35: icmp_seq=12 ttl=64 time=0.218 ms
64 bytes from 192.168.122.35: icmp_seq=13 ttl=64 time=0.148 ms
64 bytes from 192.168.122.35: icmp_seq=14 ttl=64 time=0.194 ms
64 bytes from 192.168.122.35: icmp_seq=15 ttl=64 time=0.262 ms

--- 192.168.122.35 ping statistics ---
15 packets transmitted, 4 received, 73% packet loss, time 13999ms
rtt min/avg/max/mdev = 0.148/0.205/0.262/0.043 ms

 virt-deploy ssh $NAME works only in case starting is enought fast (there is some limit for ssh what cause that this function now works as expected). I can imagine situation, that there will be some long startup -> what causes that calling this function fails

**Comment by simon3z** [comment]
I already have code for this I'll push it asap.
