### ISSUE TITLE
error: failed to mkdir on virt-deploy create <instance> <image>

### ISSUE THREAD

**Issue by screeley44** [simon3z/virt-deploy#9]
[root@miqbuild ~]# virt-deploy create test01 fedora-21
virt-builder: warning: cache /root/.cache/virt-builder: 
Unix.Unix_error(Unix.ENOENT, "mkdir", "/root/.cache/virt-builder")
virt-builder: warning: disabling the cache
[   1.0] Downloading: http://libguestfs.org/download/builder/fedora-21.xz
###### ################################################################## 100.0%

[ 205.0] Planning how to build this image
[ 205.0] Uncompressing
/tmp/vbcachec07622.txt: Success
virt-builder: error: internal error: invalid argument: some threads failed, 
see earlier errors

If reporting bugs, run virt-builder with debugging enabled and include the 
complete output:

  virt-builder -v -x [...]
Traceback (most recent call last):
  File "/usr/bin/virt-deploy", line 9, in <module>
    load_entry_point('virt-deploy==0.1.6', 'console_scripts', 'virt-deploy')()
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 143, in main
    return parse_command_line(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 138, in parse_command_line
    return COMMAND_TABLE[args.command](args)
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 41, in instance_create
    instance = driver.instance_create(args.id, args.template)
  File "/usr/lib/python2.7/site-packages/virtdeploy/drivers/libvirt.py", line 105, in instance_create
    base = _create_base(template, kwargs['arch'], repository)
  File "/usr/lib/python2.7/site-packages/virtdeploy/drivers/libvirt.py", line 264, in _create_base
    '--root-password', 'locked:disabled'))
  File "/usr/lib/python2.7/site-packages/virtdeploy/utils.py", line 36, in execute
    raise subprocess.CalledProcessError(p.returncode, args)
subprocess.CalledProcessError: Command '('virt-builder', 'fedora-21', '-o', '/var/lib/libvirt/images/_fedora-21-x86_64.qcow2', '--size', '20G', '--format', 'qcow2', '--arch', 'x86_64', '--root-password', 'locked:disabled')' returned non-zero exit status 1

**Comment by screeley44** [comment]
manually created the /root/.cache/virt-builder directory - and seem to have moved past that error, just fyi

[root@miqbuild /]# virt-deploy create test01 fedora-21
[   1.0] Downloading: http://libguestfs.org/download/builder/fedora-21.xz
######################################################################## 100.0%
[ 195.0] Planning how to build this image
[ 195.0] Uncompressing
[ 222.0] Resizing (using virt-resize) to expand the disk to 20.0G

**Comment by simon3z** [comment]
Please open a bug against virt-builder on bugzilla.

Looking at your error, the command line that was issued was:

Command '('virt-builder', 'fedora-21', '-o', '/var/lib/libvirt/images/_fedora-21-x86_64.qcow2', '--size', '20G', '--format', 'qcow2', '--arch', 'x86_64', '--root-password', 'locked:disabled')'

Thanks

**Comment by simon3z** [comment]
Closing this because it doesn't belong to virt-deploy.
